#!/usr/bin/env bash
# Script to install and configure Nginx to return "Holberton School"

# Update package lists and install nginx
apt-get update -y
apt-get install nginx -y

# Overwrite the default index.html to contain required text
echo "Holberton School for the win!" > /var/www/html/index.html

# Start nginx (without using systemctl)
service nginx start
